name: Build Docker Container
description: 'This workflow builds a Docker container and saves it as an artifact for later deployment.'
inputs:
  IMAGE_NAME:
    description: 'The name of the Docker image to build and save.'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: false
        tags: ${{ inputs.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Save Docker image
      shell: bash
      run: |
        mkdir -p image-artifact
        docker save ${{ inputs.IMAGE_NAME }}:latest > image-artifact/${{ inputs.IMAGE_NAME }}.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.IMAGE_NAME }}
        path: image-artifact/${{ inputs.IMAGE_NAME }}.tar
        retention-days: 14